"""add approval and submission fields to applications

Revision ID: 32e31f3fc373
Revises: b7ed1c6a23d2
Create Date: 2026-09-09 13:24:48.484416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e31f3fc373'
down_revision: Union[str, Sequence[str], None] = 'b7ed1c6a23d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('confirmation_details', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('failure_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('submission_screenshot', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('submission_screenshot')
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('confirmation_details')
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
