"""add status history and lifecycle fields to applications

Revision ID: b4b8596c62e2
Revises: 32e31f3fc373
Create Date: 2026-09-09 13:53:23.862878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b8596c62e2'
down_revision: Union[str, Sequence[str], None] = '32e31f3fc373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_history', sa.JSON(), nullable=True, server_default='[]'))
        batch_op.add_column(sa.Column('interview_details', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('interview_details')
        batch_op.drop_column('status_history')

    # ### end Alembic commands ###
