"""add tailored_resume and screening_questions to applications

Revision ID: b7ed1c6a23d2
Revises: ce67abb8c610
Create Date: 2026-09-09 12:33:51.895415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ed1c6a23d2'
down_revision: Union[str, Sequence[str], None] = 'ce67abb8c610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('applications')]
    with op.batch_alter_table('applications', schema=None) as batch_op:
        if 'tailored_resume' not in columns:
            batch_op.add_column(sa.Column('tailored_resume', sa.JSON(), nullable=True))
        if 'screening_questions' not in columns:
            batch_op.add_column(sa.Column('screening_questions', sa.JSON(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('screening_questions')
        batch_op.drop_column('tailored_resume')

    # ### end Alembic commands ###
